---
abstract: 'RT-Extension-ExcelFeed Extension'
author:
  - 'Best Practical Solutions, LLC <modules@bestpractical.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.21'
license: gplv2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-ExcelFeed
no_index:
  directory:
    - html
    - inc
requires:
  Excel::Writer::XLSX: 0
  perl: 5.10.1
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: '1.00'
x_module_install_rtx_version: '0.44'
x_requires_rt: 6.0.0
x_rt_too_new: 6.2.0
